---
language: node_js
node_js:
  - "0.12.2"


cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "npm --version"
  - "npm install -g bower"

install:
  - "npm install"

script:
  - npm test


